name: moneygrowai
services:
  sentiment:
    build: ./sentiment_api
    container_name: moneygrowai-sentiment
    ports: ['5002:5002']
    restart: unless-stopped
    environment:
      - HF_HOME=/models
    volumes:
      - sentiment_models:/models
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g

  article_extractor:
    build: ./article_extractor
    container_name: moneygrowai-article-extractor
    ports: ['5003:5003']
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512m

  stock_metrics:
    build: ./stock_metrics
    container_name: moneygrowai-stock-metrics
    ports: ['5004:5004']
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1g

  ticker_discovery:
    build: ./ticker_discovery
    container_name: moneygrowai-ticker-discovery
    ports: ['5005:5005']
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512m

volumes:
  sentiment_models:
